// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI_y6jvoA1_Qc2o31VCDxc7Cx16r7U9gI',
    appId: '1:1097885486130:web:4dabcb6c494f89fc92402b',
    messagingSenderId: '1097885486130',
    projectId: 'terza-spiaggia-flutton',
    authDomain: 'terza-spiaggia-flutton.firebaseapp.com',
    storageBucket: 'terza-spiaggia-flutton.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA46tdWeHCpsS1mHpehRIBTcsSOHCsjbck',
    appId: '1:1097885486130:android:7a51160757f4a8ad92402b',
    messagingSenderId: '1097885486130',
    projectId: 'terza-spiaggia-flutton',
    storageBucket: 'terza-spiaggia-flutton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd7LmuseqZ4esz9ryXBWEwIP649gOcz5I',
    appId: '1:1097885486130:ios:f50f166f81a07a1d92402b',
    messagingSenderId: '1097885486130',
    projectId: 'terza-spiaggia-flutton',
    storageBucket: 'terza-spiaggia-flutton.appspot.com',
    iosBundleId: 'com.example.terzaSpiaggiaWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd7LmuseqZ4esz9ryXBWEwIP649gOcz5I',
    appId: '1:1097885486130:ios:453b7a54c2a3891f92402b',
    messagingSenderId: '1097885486130',
    projectId: 'terza-spiaggia-flutton',
    storageBucket: 'terza-spiaggia-flutton.appspot.com',
    iosBundleId: 'com.example.terzaSpiaggiaWeb.RunnerTests',
  );
}
